version: '3.8'

services:
  regression:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:  #связь контейнера с вашей репозиторий
      - ./:/usr/workspace  # закмдываем всю тек.директорию(проект) в папку usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"  #команды для запуска
    working_dir: /usr/workspace  #на всякий случий нужно продублировать
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
        #/bin/sh -c